# https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@v3.3.0
      # https://github.com/actions/setup-node/tags
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@Jashepp'
      - name: Build package-lock
        run: npm i --package-lock-only
      - run: npm ci
      - name: Publish to GitHub Package Registry
        run: |
          npm config set scope "@Jashepp"
          npm config set @Jashepp:registry https://npm.pkg.github.com/
          npm pkg set name=@Jashepp/ce-mixinprops
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
