name: Tests

on: [push]

# https://docs.cypress.io/guides/continuous-integration/github-actions
# https://github.com/cypress-io/github-action
jobs:
  
  tests-electron:
    runs-on: ubuntu-latest
    name: Tests on Electron
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: electron
          install: true
          runTests: true
          start: npm run server
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-chrome:
    runs-on: ubuntu-latest
    name: Tests on Chrome
    container:
      # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers#cypressbrowsers
      image: cypress/browsers:node16.18.0-chrome107-ff106-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: chrome
          install: true
          runTests: true
          start: npm run server
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-firefox:
    runs-on: ubuntu-latest
    name: Tests on Firefox
    container:
      image: cypress/browsers:node16.18.0-chrome107-ff106-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: firefox
          install: true
          runTests: true
          start: npm run server
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-edge:
    runs-on: ubuntu-latest
    name: Tests on Edge
    container:
      image: cypress/browsers:node16.18.0-chrome107-ff106-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: edge
          install: true
          runTests: true
          start: npm run server
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-chrome-old:
    runs-on: ubuntu-latest
    name: Tests on Chrome v89
    container:
      # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers#cypressbrowsers
      image: cypress/browsers:node12.18.3-chrome89-ff86
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Build package-lock
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2
        with:
          browser: chrome
          install: true
          runTests: true
          start: npm run server
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-firefox-old:
    runs-on: ubuntu-latest
    name: Tests on Firefox v86
    container:
      image: cypress/browsers:node12.18.3-chrome89-ff86
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Build package-lock
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2
        with:
          browser: firefox
          install: true
          runTests: true
          start: npm run server
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
