name: Tests

on: [push]

# https://docs.cypress.io/guides/continuous-integration/github-actions
jobs:

  # Cypress Image Versions
  # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
  # Newest: https://hub.docker.com/r/cypress/browsers/tags?name=chrome
  # Oldest: https://hub.docker.com/r/cypress/browsers/tags?name=node16&ordering=-last_updated
  
  tests-electron:
    runs-on: ubuntu-latest
    name: Tests on Electron
    steps:
      # https://github.com/actions/checkout/releases
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build package-lock
        run: npm i --package-lock-only
      # https://github.com/cypress-io/github-action/releases
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          browser: electron
          install: true
          runTests: true
          start: npm run cypress:workflow
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-chrome:
    runs-on: ubuntu-latest
    name: Tests on Chrome v131
    container:
      image: cypress/browsers:node-22.11.0-chrome-131.0.6778.69-1-ff-132.0.2-edge-131.0.2903.51-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          browser: chrome
          install: true
          runTests: true
          start: npm run cypress:workflow
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-firefox:
    runs-on: ubuntu-latest
    name: Tests on Firefox v132
    container:
      image: cypress/browsers:node-22.11.0-chrome-131.0.6778.69-1-ff-132.0.2-edge-131.0.2903.51-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          browser: firefox
          install: true
          runTests: true
          start: npm run cypress:workflow
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-edge:
    runs-on: ubuntu-latest
    name: Tests on Edge v131
    container:
      image: cypress/browsers:node-22.11.0-chrome-131.0.6778.69-1-ff-132.0.2-edge-131.0.2903.51-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          browser: edge
          install: true
          runTests: true
          start: npm run cypress:workflow
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # Old Browsers
  
  tests-chrome-old:
    runs-on: ubuntu-latest
    name: Tests on Chrome v94
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build package-lock
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2
        with:
          browser: chrome
          install: true
          runTests: true
          start: npm run cypress:workflow
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests-firefox-old:
    runs-on: ubuntu-latest
    name: Tests on Firefox v93
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Build package-lock
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2
        with:
          browser: firefox
          install: true
          runTests: true
          start: npm run cypress:workflow
          wait-on: 'http://localhost:8181'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
